/* main.c — NanoSentry on STM32H7, real latency + SRAM measurement */
#include "main.h"
#include "ai_perf.h"
#include "ai_datamodel.h"        /* generated by X-CUBE-AI */
#include "ai_datamodel_config.h"
#include "ai_platform.h"
#include <stdio.h>
#include <string.h>

UART_HandleTypeDef huart3;       /* ST-Link virtual COM port */

/* X-CUBE-AI buffers */
AI_ALIGNED(4) static ai_u8 in_data[1 * 64 * 14 * 4];   /* adjust per model */
AI_ALIGNED(4) static ai_u8 out_data[1 * 4];

ai_handle network = AI_HANDLE_NULL;
ai_buffer *ai_input, *ai_output;

static void MX_USART3_UART_Init(void);   /* 115200 8N1 */
static void SystemClock_Config(void);    /* 480 MHz */

int main(void) {
    HAL_Init();
    SystemClock_Config();               /* HSE -> PLL -> 480 MHz */
    MX_USART3_UART_Init();
    perf_init();

    /* --- create & init network --- */
    ai_error err;
    static ai_buffer *ai_config = NULL; /* from generated code */
    if (ai_datamodel_create(&network, NULL) != true) {
        printf("ERR: create failed\n"); while (1);
    }
    if (!ai_datamodel_init(network, NULL, NULL)) {
        printf("ERR: init failed\n"); while (1);
    }
    ai_input  = ai_datamodel_inputs_get(network);
    ai_output = ai_datamodel_outputs_get(network);

    /* --- fill a deterministic test input --- */
    float *fin = (float *)in_data;
    for (int i = 0; i < 64*14; i++) fin[i] = 0.01f * i;

    /* --- warm-up (cache / branch predictor) --- */
    ai_datamodel_process(network, ai_input, ai_output);

    /* --- measure over N runs --- */
    const int N = 100;
    uint32_t min_c = 0xFFFFFFFF, max_c = 0, sum_c = 0;

    perf_ram_fill();                    /* watermark BEFORE inference */

    for (int r = 0; r < N; r++) {
        uint32_t t0 = perf_start();
        ai_datamodel_process(network, ai_input, ai_output);
        uint32_t t1 = perf_stop();
        uint32_t dt = t1 - t0;
        if (dt < min_c) min_c = dt;
        if (dt > max_c) max_c = dt;
        sum_c += dt;
    }

    uint32_t stack_peak = perf_ram_used_peak();

    /* --- report --- */
    float cpu_mhz = HAL_RCC_GetSysClockFreq() / 1e6f;   /* 480.0 */
    printf("\n===== NanoSentry C-MAPSS on STM32H743 =====\n");
    printf("CPU clock      : %.0f MHz\n", cpu_mhz);
    printf("Runs           : %d\n", N);
    printf("Cycles min     : %lu\n", min_c);
    printf("Cycles max     : %lu\n", max_c);
    printf("Cycles avg     : %lu\n", sum_c / N);
    printf("Latency min    : %.3f ms\n", min_c / cpu_mhz / 1000.0f);
    printf("Latency avg    : %.3f ms\n", (sum_c / N) / cpu_mhz / 1000.0f);
    printf("Latency max    : %.3f ms\n", max_c / cpu_mhz / 1000.0f);
    printf("Stack peak     : %lu bytes (%.2f KiB)\n",
           stack_peak, stack_peak / 1024.0f);
    printf("Weights+code   : see .map file (text+rodata)\n");

    while (1) { __WFI(); }
}